"""Add project detail content fields

Revision ID: 08fbe129b7c6
Revises: d653f5398210
Create Date: 2026-08-11 18:50:29.277613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fbe129b7c6'
down_revision = 'd653f5398210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenge_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('solution_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('development_process', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('results_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('lessons_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('lessons_text')
        batch_op.drop_column('results_text')
        batch_op.drop_column('development_process')
        batch_op.drop_column('solution_text')
        batch_op.drop_column('challenge_text')

    # ### end Alembic commands ###
