"""Create settings table

Revision ID: 52ffd9d95680
Revises: c719039d63e2
Create Date: 2026-07-24 03:26:54.942008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ffd9d95680'
down_revision = 'c719039d63e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('favicon', sa.String(length=255), nullable=True),
    sa.Column('github', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('twitter', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('youtube', sa.String(length=255), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.String(length=255), nullable=True),
    sa.Column('copyright_text', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('site_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tagline', sa.VARCHAR(length=255), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('favicon', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('about', sa.TEXT(), nullable=True),
    sa.Column('github', sa.VARCHAR(length=255), nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=255), nullable=True),
    sa.Column('twitter', sa.VARCHAR(length=255), nullable=True),
    sa.Column('facebook', sa.VARCHAR(length=255), nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=255), nullable=True),
    sa.Column('youtube', sa.VARCHAR(length=255), nullable=True),
    sa.Column('meta_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('meta_description', sa.TEXT(), nullable=True),
    sa.Column('meta_keywords', sa.VARCHAR(length=255), nullable=True),
    sa.Column('copyright_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settings')
    # ### end Alembic commands ###
