"""Add slug to projects

Revision ID: b8173d056cd3
Revises: 07ba6482e037
Create Date: 2026-08-06 14:25:21.287166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8173d056cd3'
down_revision = '07ba6482e037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('project_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(
            "uq_projects_slug",
            ["slug"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_projects_slug",
            type_="unique"
        )
        batch_op.drop_column('slug')
        batch_op.drop_column('duration')
        batch_op.drop_column('project_date')
        batch_op.drop_column('role')
        batch_op.drop_column('client')

    # ### end Alembic commands ###
