"""Add featured and published fields to projects

Revision ID: e783fc04b053
Revises: 52ffd9d95680
Create Date: 2026-08-04 01:38:56.857186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e783fc04b053'
down_revision = '52ffd9d95680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('display_order')
        batch_op.drop_column('published')
        batch_op.drop_column('featured')

    # ### end Alembic commands ###
